global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'spring_backend_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['backend:4001']
  - job_name: 'spring_consumer_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['consumer:4002']